### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by zen0bit** [basnijholt/dotbins#116]
##### Still getting familiar with dotbins
So not sure if isn't just something simple overlooked

### But I have a few issues
- `null` Looks like not working for me. dotbins still complain about missing tool on arm64
```
  xxh: # Bring your favorite shell wherever you go through the ssh
    repo: xxh/xxh 
    asset_patterns:
      linux:
        amd64: xxh-x86_64.AppImage
        arm64: null #TODO: No arm64/aarch64 version available
```
- Not yet figured out how to download source code `amd64: "{version}".tar.gz` from tag.
 If isn't in releases, only under tags
``` 
https://github.com/BashGui/easybashgui/archive/refs/tags/15.0.1.tar.gz
```
or
```
https://github.com/anishathalye/dotbot/archive/refs/tags/v1.21.0.tar.gz
```

  ⚠ No asset matching '15.0.1.tar.gz' found in []
