### ISSUE TITLE
How to specify paths and shell code per platform?

### ISSUE THREAD

**Issue by fluffynuts** [basnijholt/dotbins#61]
New user here, so if I missed something in the docs, please point me to it.

I'm using dotbins to try out https://github.com/nao1215/sqluv, which produces an archive where the binary inside is not called sqluv, but rather sqly. To this end, I have the following config:

```
tools_dir: ~/.dotbins
platforms:
  windows:
    - amd64

tools:
  sqluv: 
    repo: nao1215/sqluv
    path_in_archive: sqly.exe
```

Now, I'd like to be able to use the same config on my linux boxes, but the `binary_path` and `path_in_archive` seemed to require the `.exe` extensions:
1. when I add a `linux` node to the `platforms` section, with support for `amd64`, and `uvx dotbins sync` then the linux install part fails, unable to find `sqly.exe`. 
2. If I change that to `sqly`, then the windows part fails, unable to find `sqly`

Possible solutions:
1. the binary name should just be the name of the program, without any extension. On windows, `.exe` can be assumed. (easiest for the user)
2. platform subsections within tools configurations (most flexible - if the install archive has completely different names for different platforms, this can be supported)
3. ???
