### ISSUE TITLE
How to copy additional resources to the tool's config dir?

### ISSUE THREAD

**Issue by hrbtk** [basnijholt/dotbins#66]
Some tools include additional resources in the release archive (e.g. Helix has a `/runtime` directory, that [should be placed](https://docs.helix-editor.com/install.html) in `~/.config/helix/runtime` or completions in Yazi). Is there or in plans any solutions for this? Maybe something like this:
```yaml
tools:
  hx:
    repo: helix-editor/helix
    configuration:
      source_in_release: /runtime
      dest: ~/.config/helix/runtime 

```
