### ISSUE TITLE
Incorrectly grabbing arm releases

### ISSUE THREAD

**Issue by Seblerr** [basnijholt/dotbins#67]
Hi there,

Tool looks great so far, I've just had some inconsistent results that I would like to share. 

This is my config:
```
platforms:
  linux:
    - amd64

tools:
  fzf:
    repo: junegunn/fzf
    shell_code: eval "$(fzf --bash)"
  ripgrep:
    repo: BurntSushi/ripgrep
    binary_name: rg
  zoxide:
    repo: ajeetdsouza/zoxide
    shell_code: eval "$(zoxide init bash)"
  btop:
    repo: aristocratos/btop
    arch_map:
      amd64: x86_64
  neovim:
    repo: neovim/neovim
    arch_map: 
      amd64: x86_64
```

As you can see, I would like to only grab amd64 binaries. My issue is that it auto-selects arm64, despite me mapping amd64 to x86_64 for neovim, something I didn't expect.

This is from the log:
ℹ️ No asset_pattern provided for linux/amd64
🔍 Auto-detecting asset for linux/amd64
🔍 Found multiple candidates: ['nvim-linux-arm64.appimage', 'nvim-linux-x86_64.appimage'], selecting first
✅ Found asset: nvim-linux-arm64.appimage

Based on my configuration, I expected it to select the x86_64 release. Is this not the case? Do I need to specify an asset_pattern?

It would be nice to have a global setting for arch_map. If it doesn't find any matching amd64, look for x86_64. 

Oh and one more thing, for btop it downloads the x86_64 version, but I cannot run it. I get 
".dotbins/linux/amd64/bin/btop: cannot execute binary file: Exec format error", indicating that it's built for another architecture.

Thanks :)
