### ISSUE TITLE
Windows: gnu vs msvc

### ISSUE THREAD

**Issue by timendum** [basnijholt/dotbins#82]
Hi,
I'm successfully using this application, but I find difficult to select the correct version on Windows, many tools have two different "flavor" gnu or msvc, for example:

- Found multiple candidates: ['ripgrep-14.1.1-x86_64-pc-windows-gnu.zip', 'ripgrep-14.1.1-x86_64-pc-windows-msvc.zip'], selecting first
- Found multiple candidates: ['bat-v0.25.0-x86_64-pc-windows-gnu.zip', 'bat-v0.25.0-x86_64-pc-windows-msvc.zip'], selecting first
- Found multiple candidates: ['fd-v10.2.0-x86_64-pc-windows-gnu.zip', 'fd-v10.2.0-x86_64-pc-windows-msvc.zip'], selecting first
- Found multiple candidates: ['eza.exe_x86_64-pc-windows-gnu.tar.gz', 'eza.exe_x86_64-pc-windows-gnu.zip'], selecting first

Maybe the same principle already used for glibc vs musl can be used here?

I know I can use the `asset_patterns` field, but it must be done one by one and also it's time consuming and more error prone.

**Comment by basnijholt** [comment]
@timendum, I'm not a Windows native so didn't consider this. However, I'll definitely add support for this ASAP! 

Thanks for opening an issue and trying out the tool 😄

**Comment by basnijholt** [comment]
What about:

```

# Global defaults for all tools
defaults:
  prefer_appimage: true   # Linux: Prioritize AppImage format
  libc: musl              # Linux: Prefer musl over glibc
  windows_abi: msvc       # Windows: Prefer 'msvc' over 'gnu' (or vice-versa)
```

From what I read `gnu` should most likely be the default but what do you think @timendum?
