### ISSUE TITLE
Support for release tags

### ISSUE THREAD

**Issue by erichobson** [basnijholt/dotbins#89]
Would be great to see an option to allow support for a specific release tag. For example, having the option to use the nightly version of Neovim rather than latest.

**Comment by basnijholt** [comment]
In principle this would be quite easy. 

Just need to parametrize https://github.com/basnijholt/dotbins/blob/f73839c3e09cd67e1a4a16dc76fdd4d11727b856/dotbins/utils.py#L53 latest there.

**Comment by basnijholt** [comment]
I started with this in https://github.com/basnijholt/dotbins/pull/90

**Comment by basnijholt** [comment]
@erichobson, this is now possible with the `tag:` parameter!

From the [README](https://github.com/basnijholt/dotbins?tab=readme-ov-file#version-pinned-tool):

#### Version-Pinned Tool

```yaml
bat:
  repo: sharkdp/bat
  tag: v0.23.0  # Pin to specific version instead of latest
```
